### config.toml
title = "OpenPOWER Foundation"
baseURL = "https://openpower.foundation/"
theme = "openpowerfoundation"
languageCode = "en-us"
dataDir = "data"
assetDir = "assets"
PaginatePath = ""
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true
disableHugoGeneratorInject = false
enableEmoji = true

[outputs]
	home = [ "HTML", "JSON" , "RSS" ]
	specifications = [ "HTML", "JSON" ]
	ready = [ "HTML", "JSON" ]
	schedule = [ "HTML", "Calendar" , "RSS" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
[outputFormats.JSON]
	mediaType = "application/json"
	baseName = "index"
	isPlainText = true
	notAlternative = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
	hardWraps = true
	unsafe = true
	xHTML = true
[markup.highlight]
	codeFences = true
	lineNos = true
	lineNumbersInTable = true
	noClasses = false
[markup.tableOfContents]
	endLevel = 4
	ordered = false
	startLevel = 2

[imaging]
	resampleFilter = "MitchellNetravali"
	quality = 100
	anchor = "smart"
	bgColor = "#ffffff"
[imaging.exif]
	includeFields = ""
	excludeFields = ".*"
	disableDate = false
	disableLatLong = false

[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5

[taxonomies]
	tag = "tags"

[minify]
[minify.tdewolff]
[minify.tdewolff.html]
	keepWhitespace = false
