### config.toml
title = "OpenPOWER Foundation"
baseURL = "https://openpower.foundation/"
theme = "openpowerfoundation"
languageCode = "en-us"
dataDir = "data"
assetDir = "assets"
PaginatePath = ""
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true
disableHugoGeneratorInject = false
enableEmoji = true

[build]
	noJSConfigInAssets = false
#	useResourceCacheWhen = 'always'
	writeStats = true

[outputs]
	home = [ "HTML" , "JSON" , "RSS" ]
	section = [ "HTML", "JSON", "RSS" ]
	page = [ "HTML" , "JSON" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
[outputFormats.JSON]
	mediaType = "application/json"
	baseName = "index"
	isPlainText = true
	notAlternative = true

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
	definitionList = true
	footnote = true
	linkify = true
	strikethrough = true
	table = true
	taskList = true
	typographer = true
[markup.goldmark.parser]
	autoHeadingID = true
	autoHeadingIDType = 'github'
[markup.goldmark.parser.attribute]
	block = false
	title = true
[markup.goldmark.renderer]
	hardWraps = false
	unsafe = true
	xHTML = true
[markup.highlight]
	codeFences = true
	lineNos = true
	lineNumbersInTable = true
	noClasses = false
[markup.tableOfContents]
	endLevel = 4
	ordered = false
	startLevel = 2

[imaging]
	resampleFilter = "MitchellNetravali"
	quality = 100
	anchor = "smart"
	bgColor = "#ffffff"
[imaging.exif]
	includeFields = ""
	excludeFields = ".*"
	disableDate = false
	disableLatLong = false

[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5

[taxonomies]
	tag = "tags"
	category = 'categories'
	series = 'series'

[minify]
	disableCSS = false
	disableHTML = false
	disableJS = false
	disableJSON = false
	disableSVG = false
	disableXML = false
	minifyOutput = false
[minify.tdewolff]
[minify.tdewolff.html]
	keepComments = false
	keepConditionalComments = false
	keepDefaultAttrVals = true
	keepDocumentTags = true
	keepEndTags = true
	keepQuotes = false
	keepWhitespace = false
[minify.tdewolff.css]
	keepWhitespace = false
	keepCSS2 = true
	precision = 0
[minify.tdewolff.js]
	keepVarNames = false
	precision = 0
[minify.tdewolff.json]
	keepNumbers = false
	precision = 0
[minify.tdewolff.svg]
	precision = 0
[minify.tdewolff.xml]
	keepWhitespace = false

[caches]
[caches.assets]
	dir = ':resourceDir/_gen'
	maxAge = "5m"
[caches.getcsv]
	dir = ':cacheDir/:project'
	maxAge = "5m"
[caches.getjson]
	 dir = ':cacheDir/:project'
	maxAge = "5m"
	ttl = 300
[caches.getresource]
	dir = ':cacheDir/:project'
	maxAge = "5m"
[caches.images]
	dir = ':resourceDir/_gen'
	maxAge ="5m"
[caches.modules]
	dir = ':cacheDir/modules'
	maxAge = "5m"
