### navbar
[[navbar]]
	name = "About"
	identifier = "about"
	weight = -2000
[[navbar]]
	parent = "about"
	name = "Mission Statement"
	identifier = "missionstatement"
	url = "/about/missionstatement/"
	weight = -1000
[[navbar]]
	parent = "about"
	name = "Governance"
	identifier = "governance"
	url = "/about/governance/"
	weight = -900
[[navbar]]
	parent = "about"
	name = "OpenPOWER Ready™"
	identifier = "aboutready"
	url= "/about/ready/"
	weight = -800
[[navbar]]
	parent = "about"
	name = "Board of Directors"
	identifier = "bod"
	url = "/boardofdirectors/"
	weight = -700
[[navbar]]
	parent = "about"
	name = "Steering Committee"
	identifier = "steeringcommittee"
	url = "/steeringcommittee"
	weight = -600
[[navbar]]
	name = "Events"
	identifier = "events"
	url = "/events/"
	weight = -1900
[[navbar]]
	name = "Working Groups"
	identifier = "groups"
	url = "/groups/"
	weight = -1800
[[navbar]]
	name = "Members"
	identifier = "members"
	url = "/members/"
	weight = -1700
[[navbar]]
	name = "HUB"
	identifier = "hub"
	url = "/hub/"
	weight = -1600
[[navbar]]
	name = "Technical"
	identifier = "technical"
	url = "/technical/"
	weight = -1500
[[navbar]]
	parent = "technical"
	name = "Specifications"
	identifier = "specifications"
	url = "/specifications/"
	weight = -900
[[navbar]]
	parent = "technical"
	name = "OpenPOWER Ready"
	identifier = "ready"
	url = "/ready/"
	weight = -800
[[navbar]]
	parent = "technical"
	name = "Compliance"
	identifier = "compliance"
	url = "/compliance/"
	weight = -700
[[navbar]]
	parent = "technical"
	name = "Resources"
	identifier = "resources"
	url = "/resources/"
	weight= -600
[[navbar]]
	name = "Blog"
	weight = -100
	url = "/blog/"
[[navbar]]
	name = "Contact Us"
	url = "/contact/"
	weight = -10

### policy
[[policy]]
	name = "Cookie Policy"
	url = "/policy/cookie/"
	weight = -2000
[[policy]]
	name = "Privacy Policy"
	url = "/policy/privacy/"
	weight = -1900
[[policy]]
	name = "Terms of Use"
	url = "/policy/termsofuse/"
	weight = -1800
[[policy]]
	name = "Logo Policy"
	url = "/policy/logo/"
	weight = -1700
[[policy]]
	name = "Trademark Policy"
	url = "/policy/trademark/"
	weight = -1600

### governance
[[governance]]
	name = "Certificate of Incorperation"
	url = "https://files.openpower.foundation/s/xAkXWTxTxRqTeaM"
	pre = "far fa-file-pdf"
	#post = "fas fa-external-link-alt"
	weight = -1900
[[governance]]
	name = "Bylaws"
	url = "https://files.openpower.foundation/s/yYcB2C2z2pnwpcm"
	pre = "far fa-file-pdf"
	#post = "fas fa-external-link-alt"
	weight = -1800
[[governance]]
	name = "IP Rights Policy"
	url = "https://files.openpower.foundation/s/eMq2rPmnbKofrDC"
	pre = "far fa-file-pdf"
	#post = "fas fa-external-link-alt"
	weight = -1700
[[governance]]
	name = "Anti Trust Guidelines"
	url = "https://files.openpower.foundation/s/k5Hny649q3XHSqk"
	pre = "far fa-file-pdf"
	weight = -1600

###
[[code]]
	name = "Git"
	pre = "fas fa-code-branch"
	url = "https://git.openpower.foundation/"
[[code]]
	name = "GitHub"
	pre = "fab fa-github"
	url = "https://github.com/OpenPOWERFoundation"
[[code]]
	name = "GitLab"
	pre = "fab fa-gitlab"
	url = "https://gitlab.com/OpenPOWERFoundation"

###
[[discuss]]
	name = "Discuss"
	pre = "fas fa-comments"
	url = "https://discuss.openpower.foundation/auth/oidc"
[[discuss]]
	name = "Chat"
	pre = "fas fa-comment-dots"
	url = "https://chat.openpower.foundation"
[[discuss]]
	name = "Slack"
	pre = "fab fa-slack"
	url = "https://openpowerfoundation.slack.com"

### social
[[social]]
	name = "Twitter"
	pre = "fab fa-twitter"
	url = "https://twitter.com/OpenPOWERorg"
	weight = -2000
[[social]]
	name = "Facebook"
	pre = "fab fa-facebook"
	url = "https://www.facebook.com/openpower"
	weight = -1900
[[social]]
	name = "LinkedIN"
	pre = "fab fa-linkedin-in"
	url = "https://www.linkedin.com/company/openpower-foundation/?viewAsMember=true"
	weight = -1800
[[social]]
	name = "YouTube"
	pre = "fab fa-youtube"
	url = "https://www.youtube.com/channel/UCNVcHm09eXVbvUzZkQs0_Sg"
	weight = -1700
