### navbar

[[navbar]]
	name = "About"
	identifier = "about"
	weight = -2000
[[navbar]]
	parent = "about"
	name = "Mission Statement"
	identifier = "missionstatement"
	url = "/about/missionstatement/"
	weight = -1000
[[navbar]]
	parent = "about"
	name = "Governance"
	identifier = "governance"
	url = "/about/governance/"
	weight = -900
[[navbar]]
	parent = "about"
	name = "Board of Directors"
	identifier = "bod"
	url = "/boardofdirectors/"
	weight = -800
[[navbar]]
	parent = "about"
	name = "Steering Committee"
	identifier = "steeringcommittee"
	url = "/steeringcommittee"
	weight = -700

[[navbar]]
	name = "Events"
	identifier = "events"
	url = "/events/"
	weight = -1900

[[navbar]]
	name = "Working Groups"
	identifier = "groups"
	url = "/groups/"
	weight = -1800

[[navbar]]
	name = "Members"
	identifier = "members"
	url = "/members/"
	weight = -1700

[[navbar]]
	name = "HUB"
	identifier = "hub"
	url = "/hub/"
	weight = -1600

[[navbar]]
	name = "Technical"
	identifier = "resources"
	weight = -1500
[[navbar]]
	parent = "resources"
	name = "Technical Specifications"
	identifier = "technicalspecifications"
	url = "/specifications/"
	weight = -900
[[navbar]]
	parent = "resources"
	name = "OpenPOWER Ready"
	identifier = "ready"
	url = "/ready/"
	weight = -700

### social
[[social]]
	name = "Twitter"
	pre = "fab fa-twitter"
	url = "https://twitter.com/OpenPOWERorg"
	weight = -2000
[[social]]
	name = "Facebook"
	pre = "fab fa-facebook"
	url = "https://www.facebook.com/openpower"
	weight = -1900
[[social]]
	name = "LinkedIN"
	pre = "fab fa-linkedin-in"
	url = "https://www.linkedin.com/company/openpower-foundation/?viewAsMember=true"
	weight = -1800
[[social]]
	name = "YouTube"
	pre = "fab fa-youtube"
	url = "https://www.youtube.com/channel/UCNVcHm09eXVbvUzZkQs0_Sg"
	weight = -1700
