[[navbar]]
	name = "About"
	identifier = "about"
	weight = -2000
[[navbar]]
	parent = "about"
	name = "Board of Directors"
	identifier = "bod"
	url = "/boardofdirectors/"
	weight = -900
[[navbar]]
	parent = "about"
	name = "Steering Committee"
	identifier = "steeringcommittee"
	url = "/steeringcommittee"
	weight = -800
[[navbar]]
	parent = "about"
	name = "Governance"
	identifier = "governance"
	url = "/about/governance/"
	weight = -700
[[navbar]]
	parent = "about"
	name = "Mission Statement"
	identifier = "missionstatement"
	url = "/about/missionstatement/"
	weight = -600

[[navbar]]
	name = "Events"
	identifier = "events"
	url = "/events/"
	weight = -1900

[[navbar]]
	name = "Working Groups"
	identifier = "groups"
	url = "/groups/"
	weight = -1800

[[navbar]]
	name = "Members"
	identifier = "members"
	url = "/members/"
	weight = -1700

[[navbar]]
	name = "Join"
	identifier = "join"
	url = "/join/"
	weight = -1850


[[navbar]]
	name = "HUB"
	identifier = "hub"
	url = "/hub/"
	weight = -1700

[[navbar]]
	name = "Technical"
	identifier = "resources"
	weight = -1500
[[navbar]]
	parent = "resources"
	name = "Technical Specifications"
	identifier = "technicalspecifications"
	url = "/specifications/"
	weight = -900
[[navbar]]
	parent = "resources"
	name = "OpenPOWER Ready"
	identifier = "ready"
	url = "/ready/"
	weight = -700
