#!parms.toml
[forms.contact]
	URI = "http://localhost:8080/forms/contactus/opf"
[forms.hub]
	URI = "http://localhost:8080/forms/hub/opf"
[forms.isarfc]
	URI = "http://localhost:8080/forms/isarfc/opf"
[forms.passport]
	URI = "http://localhost:8080/forms/passport/opf"
[forms.mailmonk]
	URI = "http://localhost:9000/subscription/form"
