#!parms.toml
[analytics.piwik]
	URI = "stats.vantosh.com"
	ID = "69"
[forms.contact]
	URI = "https://webscripts.vantosh.com/forms/contactus/prod/opf"
[forms.hub]
	URI = "https://webscripts.vantosh.com/forms/hub/prod/opf"
[forms.isarfc]
	URI = "https://webscripts.vantosh.com/forms/isarfc/prod/opf"
[forms.passport]
	URI = "https://webscripts.vantosh.com/forms/passport/prod/opf"
[forms.mailmonk]
	URI = "https://mailing.openpower.foundation/subscription/form"
