#!parms.toml
[analytics.piwik]
	URI = "stats.vantosh.com"
	ID = "69"
[forms.contact]
	URI = "https://webscripts.vantosh.com/forms/contact/opfm"
[forms.hub]
	URI = "https://webscripts.vantosh.com/forms/hub/prod/opf"

